### ISSUE TITLE
Re-calculate time from timewarrior

### ISSUE THREAD

**Issue by hardliner66** [gkssjovi/trackwarrior#2]
Sometimes I forget to start or stop a task. When this happens, I have to correct the time in timewarrior and then manually edit the time in a task so it matches up again.

It would be cool to have a timewarrior extension which could re-export all tracked times to taskwarrior and do that recalculation.

**Comment by gkssjovi** [comment]
When I forget to start the tracking, do this on the current task.
1. Start the task again, then stop the task.
2. Open the terminal and run this command for the timewarrior ` timew lengthen @1 60mins` . @1 Means the last task.
3. When you start the task again, the time spend of the task will be updated.

I hope this helps you.

**Comment by hardliner66** [comment]
Thanks for the quick response. Does that mean that trackwarrior already update it's values on task start, after I edited the time in timewarrior?

**Comment by gkssjovi** [comment]
Trackwarrior will update it's value based on the timewarrior. If you modify the time in timewarrior the changes will be visible in taskwarrior. Try to give a try and test, I think it should work for you as well.

**Comment by hardliner66** [comment]
Thanks. This helps a lot. I'll try it later.

Btw. I made a docker container for trackwarrior with tasksh as interface. Would you be interested to add something like that to this repository? If yes I will prepare a pull request, if no I'll just keep it separate.

**Comment by gkssjovi** [comment]
Sure, no problem. Can you create a pull request to see the changes ?
For the interface I use taskwarrior TUI

**Comment by hardliner66** [comment]
It worked. I created two pull request. One is to make it possible to use tags like +update to trigger an update of the tracked time. The other one is for docker. I updated my the container to include taskwarrior tui as well.

**Comment by gkssjovi** [comment]
Thank you, I will try to check them those days and then approve them.

**Comment by gkssjovi** [comment]
I have merge the changes into master. Great work !
