### ISSUE TITLE
Push to docker

### ISSUE THREAD

**Issue by hardliner66** [gkssjovi/trackwarrior#7]
It would be nice if you could create the docker user and repository so that others can pull from there.

There is a github workflow to automatically push to dockerhub when a tag is created. So once the account and repo on dockerhub are created, you just need to add DOCKER_USERNAME and DOCKER_PASSWORD to the repo secrets.

The workflow currently assumes username trackwarrior and repo name trackwarrior. If you want to change that to something like gkssjovi/trackwarrior we would need to replace all instances in the workflow, scripts and readme.

**Comment by gkssjovi** [comment]
How to do that? On docker hub ? 
Can you create one ?

**Comment by hardliner66** [comment]
In theory I could create the account, but it would be better if the owner of the github repo is also the owner of the dockerhub repo.
You can create an account at https://hub.docker.com/

I think it might be best to name the account `trackwarrior`, so it's easier for people to remember.

When you created the account, you can create a repository:
![image](https://user-images.githubusercontent.com/2937272/187867150-b2108677-5ebc-4c51-a9f4-33abc3d81eb6.png)
![image](https://user-images.githubusercontent.com/2937272/187867881-08bd57ba-4fcc-4f14-b5cb-9edd1d34157c.png)

The name of the repository should be `trackwarrior` as well.

Finally, you need to create two repo secrets:
![image](https://user-images.githubusercontent.com/2937272/187868652-788680cb-9e2d-4f21-8c97-06c3b1cc0ee9.png)

One for `DOCKER_USERNAME`:
![image](https://user-images.githubusercontent.com/2937272/187868838-3bc1ace1-d9b8-49af-b6b5-6f10ba2a8537.png)

and another one for `DOCKER_PASSWORD`.

Where `DOCKER_USERNAME` is your dockerhub username (e.g.: trackwarrior) and `DOCKER_PASSWORD` is the password you have chosen. These secrets are hidden and only visible to CI.

Finally, just create a tag and push it to the repo:
```sh
git tag v1.0.0
git push --tags
```

The CI will build the docker container and upload it automatically to dockerhub.

**Comment by hardliner66** [comment]
@gkssjovi I created the docker account. But I need to either get access to this repository to set the correct password or another way of communicating the password to you. Alternatively, what do you think about creating a github org named trackwarrior to host the code as well? That would give an easier URL to remember and make everything look more streamlined.

**Comment by hardliner66** [comment]
To simplify things, I went ahead and created the docker repository and a `trackwarrior` organization on github. I invited you there as a owner, so you have full rights on everything. I can even remove myself from the org if you dont want me to have permissions.

In the future I can change the docker account to use your e-mail instead of mine, if you want full access to everything.

If that's fine for you, you can update this repositories README to link to the organization repo https://github.com/trackwarrior/trackwarrior and archive afterwards. This makes it easier to know which is the actively worked on/maintained repo.

If that's not what you want, I can remove all those things again, but then you would need to configure those things yourself.

**Comment by gkssjovi** [comment]
Hello

That is fine with me :)
Please create a pull request for the README.md file

Thx

**Comment by hardliner66** [comment]
I already created a pull request for the `README.md`.

The change is already in the other repository as well.

**Comment by gkssjovi** [comment]
Now it's merged. I have approved it.
Thank you

**Comment by hardliner66** [comment]
It would be nice if we could move all further development to https://github.com/trackwarrior/trackwarrior, as it's the repo that is used for uploading the docker containers as well.
